"""add channel sources table

Revision ID: 2997af3e9203
Revises: 28dfce434c04
Create Date: 2026-09-13 04:56:27.264911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2997af3e9203'
down_revision: Union[str, Sequence[str], None] = '28dfce434c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop', sa.String(length=64), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account'),
    sa.UniqueConstraint('source_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_sources')
    # ### end Alembic commands ###
