"""add channel videos table

Revision ID: d8fedc5eb15f
Revises: 7327b91b731a
Create Date: 2026-09-13 12:24:47.953539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fedc5eb15f'
down_revision: Union[str, Sequence[str], None] = '7327b91b731a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_videos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('shop', sa.String(length=64), nullable=False),
    sa.Column('account', sa.String(length=128), nullable=False),
    sa.Column('video_title', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_url')
    )
    op.create_index(op.f('ix_channel_videos_account'), 'channel_videos', ['account'], unique=False)
    op.create_index(op.f('ix_channel_videos_shop'), 'channel_videos', ['shop'], unique=False)
    op.create_index(op.f('ix_channel_videos_source_id'), 'channel_videos', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_videos_source_id'), table_name='channel_videos')
    op.drop_index(op.f('ix_channel_videos_shop'), table_name='channel_videos')
    op.drop_index(op.f('ix_channel_videos_account'), table_name='channel_videos')
    op.drop_table('channel_videos')
    # ### end Alembic commands ###
